import type { Dictionary } from "./en";

/** Simplified Chinese — the Malaysian standard. Typed against `Dictionary`, so
 * a missing key is a compile error rather than a blank on a customer's screen. */
export const zh: Dictionary = {
	meta: {
		title: "EzCabinet · 三维设计您的厨房",
		description:
			"将真实的 EzCabinet 橱柜放入您自己房间的模型中，从各个角度查看，并即时获得报价。无需前往展厅。",
	},
	common: {
		brand: "EzCabinet",
		back: "返回",
		next: "下一步",
		close: "关闭",
		language: "语言",
		comingSoon: "即将推出",
	},
	landing: {
		nav: {
			howItWorks: "运作方式",
			gallery: "作品集",
			finishes: "板材选择",
			faq: "常见问题",
			tutorials: "教学视频",
			menu: "菜单",
			startPlanning: "开始设计",
			admin: "管理员",
		},
		hero: {
			eyebrow: "免费试用 · 无需注册",
			titleBeforeAccent: "设计您的厨房，尽在",
			titleAccent: "3D",
			subtitle:
				"将真实的 EzCabinet 橱柜放入您自己的房间，边搭配边看价格变化，完成后直接把方案发给我们。",
			cta: "开始设计",
			howItWorks: "运作方式",
			alt: "一间已完工的 EzCabinet 厨房",
		},
		facts: {
			cabinetsFromLabel: "橱柜起价",
			typicalDeliveryValue: "4 至 6 周",
			typicalDeliveryLabel: "平均交货时间",
			warrantyValue: "5 年",
			warrantyLabel: "五金与结构保修",
			noAccountValue: "无需注册",
			noAccountLabel: "即可设计与报价",
		},
		how: {
			heading: "从空白墙面到报价，只需三步",
			step1Title: "选择您的房间",
			step1Detail: "选择厨房、客厅、卧室或玄关，输入您墙面的实际尺寸。",
			step2Title: "按比例放入橱柜",
			step2Detail:
				"在 3D 场景中排列真实的 EzCabinet 橱柜，随意切换板材，直到满意为止。",
			step3Title: "即时获取报价",
			step3Detail:
				"搭配的同时即可看到实时价格，完成后直接把方案发给我们的团队。",
		},
		gallery: {
			heading: "按房间浏览",
			subtitle: "每个房间都以真实的 EzCabinet 尺寸和现成的布局开始设计。",
			roomAlt: "{room}橱柜",
			roomSubtitle: {
				kitchen: "真实的 EzCabinet 尺寸",
				living: "电视柜与展示柜",
				bedroom: "衣柜",
				foyer: "鞋柜与长凳",
			},
		},
		finishes: {
			heading: "板材与颜色",
			subtitle: "在设计工具中即可为任何橱柜更换板材。",
		},
		faq: {
			heading: "常见问题",
			q1: "送货需要多久？",
			a1: "确认方案后，大部分订单会在 4 至 6 周内送达，具体视板材和橱柜尺寸而定。",
			q2: "可以顺便安装橱柜吗？",
			a2: "可以。当您把方案发给我们的团队做最终报价时，可以加上安装服务。",
			q3: "橱柜是用什么材料制成的？",
			a3: "实心柜体，可选贴皮、防火板或喷漆等多种表面处理，完整款式请见设计工具。",
			q4: "下单后还能更改设计吗？",
			a4: "只要还没开始生产，修改都是免费的。我们的团队会先与您确认方案。",
			q5: "有提供保修吗？",
			a5: "每个橱柜均享有 5 年五金与结构保修。",
		},
		closing: {
			heading: "您的墙面，您的尺寸，您的价格。只需大约五分钟。",
			subtitle: "无需安装任何软件，也无需注册账号。",
			cta: "开始设计",
		},
		footer: {
			tagline: "量身定制的橱柜，以 3D 设计，并按您房间的实际尺寸打造。",
			productHeading: "产品",
			startPlanning: "开始设计",
			gallery: "作品集",
			faq: "常见问题",
			tutorials: "教学视频",
			contactHeading: "联系我们",
			email: "hello@ezcabinet.com",
			privacy: "隐私声明",
			adminSignIn: "管理员登录",
			copyright: "© 2026 {brand}。版权所有。",
		},
	},
	planner: {
		crumbs: {
			roomPlanner: "房间设计",
			studio: "设计工作台",
			quote: "报价",
		},
		breadcrumbAriaLabel: "面包屑导航",
		admin: "管理员",
		changeRoom: "更换房间",
		diyTutorials: "DIY 教学视频",
		clear: "清除",
		dimensionAriaSuffix: "{label}（单位：毫米）",
		tools: {
			ariaLabel: "工具",
			select: "选择",
			add: "添加",
			room: "房间",
			measure: "测量",
			view: "视图",
			doors: "门板",
			defaults: "设置",
			selectTitle: "选择并移动柜子",
			addTitle: "添加柜子",
			roomTitle: "房间尺寸：墙面、层高与进深",
			measureTitle: "测量两点之间的距离",
			viewTitle: "视图：3D、立面或平面",
			doorsTitle: "门板：打开、关闭或隐藏",
			defaultsTitle: "整排的默认设置",
		},
		panel: {
			close: "关闭面板",
			addTitle: "添加柜子",
			addHint: "点击即可加到整排末端，也可以拖到墙上。",
			viewTitle: "视图",
			viewHint: "房间的呈现方式。",
			threeDHint: "看看房间完成后的样子。",
			elevationHint: "正面平视——最适合确定尺寸。",
			planHint: "俯视——最适合看进深与通道。",
			resetView: "重置视角",
			resetViewHint: "重新框住整排橱柜。",
			doorsTitle: "门板",
			doorsHint: "适用于所有柜子。单个柜子的门板由它自己的“打开门板”操作控制。",
			defaultsTitle: "整排的默认设置",
			defaultsHint: "设置一次，适用于所有柜子——无论是否已摆放。",
		},
		start: {
			heading: "您想设计哪个房间？",
			subtitle:
				"选择一个房间，即可在空白墙面上使用真实的 EzCabinet 尺寸开始设计。",
			roomIconAlt: "{room}图标",
			roomSubtitle: {
				kitchen: "真实的 EzCabinet 尺寸",
				living: "电视柜与展示柜",
				bedroom: "衣柜",
				foyer: "鞋柜与长凳",
			},
			cta: "开始设计",
		},
		room: {
			fitFree: "墙面还剩 {mm} 毫米。",
			fitOver: "整排比墙面长 {mm} 毫米。请移除一个柜子或加长墙面。",
			moreSettings: "踢脚板、端板、悬挂高度……",
			next: "下一步：添加柜子",
			heading: "房间设置",
			subtitle: "决定每个橱柜可容纳的空间。",
			ceiling: "天花板高度",
			shape: "布局",
			shapeRect: "矩形",
			shapeL: "L 形",
			shapeLMirror: "L 形（镜像）",
			shapeLocked:
				"灰色的形状会让某个柜子失去墙面——位于新的转角处，或超出较短墙面的末端。请先移动它。",
			wallName: "墙 {n}",
			paint: "墙漆",
			paintNone: "不上色",
			paintAria: "墙 {n} 的颜色",
			paintCustom: "自选颜色",
			paintingWall: "正在为墙 {n} 上色",
			paintAll: "应用到所有墙面",
			wallsHint: "点按房间中的墙面，或平面图中的尺寸，即可修改。",
			wallUnitsHangAt: "吊柜悬挂高度",
			wallUnitsAria: "吊柜",
			hanging: "悬挂式",
			toCeiling: "顶天式",
			undersidesNote:
				"柜底高度为 {height} 毫米——柜体顶天而立，并以收边线封顶。",
			flushWallUnitTops: "将吊柜顶部与高柜对齐",
			addTallFirst: "请先添加高柜或冰箱柜",
			baseUnitsAria: "地柜",
			skirted: "带踢脚板",
			legsShown: "外露支脚",
			kickBoardNote: "踢脚板沿地面铺设，遮住可调支脚。",
			levellersNote: "可调支脚外露于柜体下方。",
			doorsAria: "柜门",
			doorsClosed: "关闭柜门",
			doorsOpen: "打开柜门",
			doorsHidden: "隐藏柜门",
			frontsOffNote:
				"移除门板后，整排布局可一次看清。同一竖梃上的两扇门无法同时打开，因此此视图选择将门板移除。",
			interiorsShownNote: "此时可看到搁板与内部结构。测量时会重新关闭柜门。",
			openDoorsNote: "打开柜门或移除门板，即可看到整排布局的内部。",
			overhangWarning:
				"此布局超出墙面 {overhang} 毫米——请先缩小下方的间隙，或移除一个橱柜。",
		},
		view: {
			ariaLabel: "视图",
			threeD: "3D 视图",
			elevation: "立面图",
			plan: "平面图",
		},
		addCabinets: {
			targetWall: "添加到",
			targetWallHint: "正在添加到墙 {n}。点按房间中的另一面墙即可在那里布置。",
			heading: "添加橱柜",
			subtitle: "拖曳到墙面上。稍后再选择尺寸与门板。",
			sizeRange: "{min}–{max} 毫米 · 起价 {price}",
			widthPrice: "{width} 毫米 · {price}",
			categories: {
				BASE_CABINET: "地柜",
				WALL_CABINET: "吊柜",
				TALL_CABINET: "高柜",
				DRAWER_BASE: "抽屉地柜",
				FRIDGE_HOUSING: "冰箱柜",
				CORNER_BASE_CABINET: "转角地柜",
				CORNER_WALL_CABINET: "转角吊柜",
			},
		},
		canvas: {
			selectHint: "点击柜子即可选中 · 右键查看操作",
			runOfWall: "{wall} 米墙面上的 {run} 米布局",
			loading: "正在载入三维视图……",
		},
		measure: {
			tooltip:
				"点击橱柜上的两个点——角点、边缘中点或表面——即可测量两点之间的距离",
			measuring: "测量中……",
			measure: "测量",
			constrainLabel: "限制测量方向",
			clickToStart: "点击一个点以开始测量",
			clickSecondPoint: "点击第二个点",
			hintMeasuring:
				"点击橱柜上的两个点——角点、边缘中点或表面。自动模式会将第二个点锁定在您所测量的方向上；自由模式则同时读取三个方向的数值。",
			hintDefault: "点击橱柜可更改尺寸或门板。沿墙面拖曳可移动位置。",
		},
		selection: {
			hangAtThis: "此柜悬挂于",
			swapLeft: "与左边的柜子对调",
			swapRight: "与右边的柜子对调",
			swapHint:
				"方向键让它与旁边的柜子对调，整排始终保持紧凑。若要移到有空位的地方，请直接输入数值。",
			verbResize: "改尺寸",
			verbReplace: "更换",
			verbMove: "移动",
			verbOpenDoors: "打开门板",
			verbCloseDoors: "关上门板",
			moveMeta: "方向键 + 毫米",
			replaceHeading: "更换为",
			positionHeading: "位置",
			gapLeft: "左侧间距",
			gapRight: "右侧间距",
			editGap: "修改距离",
			widthHint:
				"相邻柜子不会移动——放不下的尺寸会变灰。{name} 提供 {n} 种宽度。",
			moveHintFloor: "方向键让它沿墙滑动，也可把它抬离地面。圆环可旋转它。",
			moveHintWall: "方向键让它沿墙滑动，并设定悬挂高度。圆环可旋转它。",
			hangsAt: "悬挂于 {mm} 毫米",
			standsAt: "此柜离地",
			turnedBy: "旋转",
			sizeRangeMeta: "{min}–{max} 毫米",
			heading: "已选橱柜",
			emptyHint: "点击房间中的橱柜以调整尺寸或更换门板。",
			nameWidth: "{name} · {width} 毫米",
			width: "宽度",
			noRoom: "空间不足",
			front: "门板",
			swing: "开门方向",
			closeDoor: "关闭柜门",
			openDoor: "打开柜门",
			hingeLeft: "左侧铰链",
			hingeRight: "右侧铰链",
			duplicate: "复制",
			remove: "移除",
			nSelected: "已选择 {n} 个橱柜",
			removeAll: "全部移除（{n} 个）",
		},
		design: {
			heading: "本设计",
			hint: "点击房间里的柜子，即可改尺寸、更换或移动。",
			room: "房间",
			wall: "墙面",
			run: "整排",
			wallFree: "剩余墙面",
			overBy: "超出 {mm} 毫米",
			finish: "饰面",
			addCabinet: "添加柜子",
		},
		finish: {
			heading: "整排门板颜色",
			currentLabel: "{label} · 整个房间统一色调",
		},
		run: {
			heading: "您的布局 · {count} {unit}",
			closeGaps: "缩小间隙",
			closeGapsCount: "缩小间隙（{n}）",
			selectAria: "选择{name}",
			noDoorInline: "不装门板",
			emptyHint: "尚未放置任何橱柜——请将柜体拖曳到墙面上。",
			reset: "重置此房间",
			resetConfirm:
				"要重置此房间吗？所有柜子、房间形状和墙面颜色都会被清除，且无法撤销。",
		},
		price: {
			breakdown: "明细",
			breakdownTitle: "{total} 的构成",
			trimStrip: "封顶收边条",
			skirtingBoard: "遮盖支脚的踢脚板",
			endPanels: "每个外露柜体侧面的收边板",
			and: "以及",
			includedAboveSingular: "已计入以上价格。",
			includedAbovePlural: "均已计入以上价格。",
			estimatedTotal: "预估总价",
			estimateBadge: "预估",
			placeholderNote: "暂定价格——须经 EzCabinet 确认后方为正式报价。",
			cta: "为此设计索取报价",
			lines: {
				carcasses: "柜体",
				doors: "门板",
				worktop: "台面",
				ceilingTrim: "封顶收边条",
				skirting: "踢脚板",
				endPanels: "收边板",
			},
			detail: {
				unitCountOne: "{count} 个单元",
				unitCountOther: "{count} 个单元",
				noDoors: "尚未选择",
				doorCountOne: "{count} 扇门",
				doorCountOther: "{count} 扇门",
				lengthRate: "{ft} 英尺 @ RM {rate}/英尺",
				endPanelsOne: "{count} 块，用于外露侧面",
				endPanelsOther: "{count} 块，用于外露侧面",
			},
		},
		unit: "个单元",
		units: "个单元",
	},
	quote: {
		loading: "载入中……",
		backToEditing: "返回编辑",
		savedHeading: "已保存——仅供演示",
		savedBody:
			"潜在客户功能尚未与 EzCabinet 系统对接（属于本项目后续阶段）。此次操作未发送任何内容。",
		heading: "订购这间{room}",
		description: "下单后以银行转账付款。设计师会在制作前到场核实您的尺寸。",
		fullName: "姓名",
		phone: "电话号码（WhatsApp）",
		email: "电子邮箱",
		area: "所在地区",
		siteAddress: "送货地址",
		addressNotes: "进出须知——单位、门禁密码、电梯",
		remeasureNote:
			"我了解设计师会在制作前到场重新测量，如设计需要更改会先联系我。",
		whatsappOptIn: "通过 WhatsApp 向此号码发送订单进度",
		saved: "已保存",
		submitCta: "继续付款",
		errorNameRequired: "请输入您的全名。",
		errorPhoneRequired: "请输入我们可以联系到您的电话号码。",
		errorAddressRequired: "请输入送货地址。",
		errorAddressShort: "这个地址似乎太短了。",
		errorRemeasure: "请勾选此项以继续。",
		submitting: "正在下单……",
		descriptionOnline: "设计师会在施工前到现场重新测量。",
		sectionContact: "联系方式",
		sectionDelivery: "送货",
		sectionPayment: "付款",
		payCta: "支付 · {amount}",
		paying: "正在处理付款……",
		paymentSecure: "付款由 Stripe 处理。我们不会看到您的银行卡或网银登录信息。",
		paymentFailedTitle: "付款未成功",
		paymentFailedBody:
			"未产生任何扣款。您的资料已保存。请重试或选择其他付款方式。",
		errorEmailRequired: "请输入用于接收收据的电子邮件。",
		errorEmailInvalid: "电子邮件地址似乎不正确。",
		signInTitle: "登录后即可下单",
		signInBody:
			"每份订单都归属一个账户，方便您之后查看进度。您的设计已保存，登录后会直接回到这里。",
		oneOffPayment: "一次性付款",
		errorGeneric: "无法下单，请再试一次。",
		errorPhone: "电话号码似乎不正确，请包含区号，例如 012-345 6789。",
		errorDesign: "此设计中有部分内容无法按现状订购。请返回编辑并检查您的橱柜。",
		subtotal: "橱柜",
		delivery: "运费",
		total: "总计",
		summary: "{room} · 整排 {runs} · {count} {unit}",
		noFrontsYet: "尚未选择门板",
		frontsLabel: "{label}门板",
		mixedFronts: "多种门板",
		estimatedTotal: "预估总价",
		estimateBadge: "预估",
		notAQuoteNote: "此价格须经现场确认后方为正式报价。",
	},
	tutorials: {
		eyebrow: "学习",
		heading: "DIY 教学视频",
		subtitle:
			"简短视频，教您安装我们提供的每一种橱柜，从地柜、吊柜到电视柜和衣柜。",
		allTypes: "所有类型",
		emptyNoTutorials: "教学视频正在拍摄中，请稍后再来查看。",
		emptyNoMatches: "这类橱柜暂时还没有视频。",
		loadingPlayer: "正在载入播放器……",
		copyright: "© {brand} 版权所有",
		backToSite: "返回主页",
		categories: {
			base: "地柜",
			wall: "吊柜",
			tall: "高柜",
			drawer: "抽屉地柜",
			fridge: "冰箱柜",
			tv: "电视柜",
			wardrobe: "衣柜",
			shoe: "鞋柜",
		},
	},
	order: {
		headingConfirming: "正在确认您的付款",
		bodyConfirming:
			"谢谢——我们正在等待支付服务商确认，通常只需几秒钟，此页面会自动更新。您无需再次付款。",
		headingProcessing: "正在等待银行确认",
		bodyProcessing:
			"您的银行尚未确认。如果款项已从您的账户扣除，确认后会显示在这里，通常在 30 分钟内。您无需再次付款。",
		bodyAwaitingOnline: "谢谢，您的订单已保存。请支付以下总额以确认订单。",
		payOnlineHeading: "在线付款",
		payOnlineCta: "支付 {amount}",
		payOnlineError: "无法加载付款表单。请刷新页面重试。",
		headingAwaiting: "订单已提交——等待付款",
		bodyAwaiting: "谢谢，您的订单已保存。请转账以下总额以确认订单。",
		headingPaid: "订单已确认",
		bodyPaid: "已收到付款，您的橱柜即将进入生产。",
		headingCancelled: "订单已取消",
		bodyCancelled: "此订单已取消。如非您预期，请与我们联系。",
		copyOrderId: "复制订单编号",
		copied: "已复制",
		summaryHeading: "订单摘要",
		qty: "数量 {count}",
		subtotal: "小计",
		delivery: "运费",
		totalPaid: "已付总额",
		addressHeading: "送货地址",
		payHeading: "银行转账付款",
		payBank: "银行",
		payAccountName: "账户名称",
		payAccountNumber: "账户号码",
		payReference: "转账备注",
		payAmount: "金额",
		payNote:
			"请以订单编号作为转账备注，方便我们核对付款。款项到账后我们会联系您，通常在一个工作日内。",
		stagePaid: "已收到付款",
		stageMeasureDetail: "设计师会在制作前核实您的尺寸。",
		stages: {
			MEASURE: "到场重新测量",
			CUTTING: "板材切割",
			EDGING: "封边",
			ASSEMBLY: "组装",
			QC: "质量检查",
			READY: "准备送货",
		},
		stageDelivery: "送货到府",
		trackDelivery: "追踪您的配送",
		progressHeading: "进度",
		totalDue: "应付总额",
	},
	track: {
		headingPlaced: "订单已确认",
		bodyPlaced: "感谢您的订购，我们已收到订单并正在备货。",
		headingDelivered: "已送达",
		bodyDelivered: "您的橱柜已送达。感谢您的选择。",
		headingStopped: "配送暂停",
		bodyStopped: "此次配送未能完成，我们的团队会致电与您跟进。",
		orderId: "订单编号",
		copyOrderId: "复制订单编号",
		copied: "已复制",
		summaryHeading: "订单摘要",
		qty: "数量 {count}",
		noItems: "出货清单仍在整理中。",
		addressHeading: "配送地址",
		statusHeading: "配送状态",
		etaHeading: "预计送达",
		etaPending: "待确认",
		carrierRef: "{carrier} · 单号 {reference}",
		carrierBooked: "由 {carrier} 配送",
		timelineEmpty: "暂无记录。",
		awaitingHeading: "配送",
		awaitingEtaHeading: "预计时段",
		awaitingStatus: "安排中",
		awaitingCarrier: "尚未安排物流伙伴",
		stagePlaced: "订单已确认",
		stageBuilding: "橱柜制作中",
		stageBuildingDetail: "目前在工厂生产",
		awaitingNote:
			"橱柜完工后我们会安排物流伙伴。届时追踪信息会显示在此页，我们也会把链接发送给您。",
		awaitingNoteSub: "通常在配送前两至三个工作日安排。在此之前您无需做任何事。",
		backToPlanner: "返回设计工具",
		backHome: "返回主页",
		status: {
			DRAFT: "安排中",
			QUOTED: "安排中",
			BOOKED: "订单已确认",
			DRIVER_ASSIGNED: "已安排司机",
			PICKED_UP: "已取件",
			IN_TRANSIT: "运送中",
			DELIVERED: "已送达",
			CANCELLED: "已取消",
			FAILED: "配送失败",
		},
	},
	consent: {
		title: "帮助我们改进设计工具",
		body: "允许我们记录您使用设计工具的方式及出现的错误，数据由位于欧盟（马来西亚境外）的 PostHog 处理。您输入的任何内容都不会被记录。若您拒绝，我们只会在不使用 Cookie 的情况下统计访问次数。",
		accept: "允许",
		reject: "拒绝",
		learnMore: "隐私声明",
	},
	privacy: {
		title: "隐私声明",
		draft: "草稿——须经 EzCabinet Sdn Bhd 审核后方可生效。",
		intro:
			"本声明说明您使用 EzCabinet 设计工具时我们会记录哪些信息，以及原因。",
		purposeHeading: "目的",
		purpose: "找出设计工具中令人困惑或出错的地方，并加以修复。",
		collectHeading: "我们记录的内容",
		collect:
			"您打开的页面、您所做的设计选择（房间、橱柜、尺寸、饰面、门板）、预估价格、设备和浏览器类型，以及设计工具出现的技术错误。若您同意，当发生错误时我们还会保留一段简短的页面录像（您输入的所有内容均会被隐藏），以便了解问题所在。",
		notCollectHeading: "我们绝不记录的内容",
		notCollect:
			"报价表单中的姓名、电话号码、电子邮箱或地址不会发送给我们的分析服务提供商。分析数据中不会保留您的 IP 地址。",
		whereHeading: "由谁处理，在哪里处理",
		where:
			"使用数据由 PostHog Inc. 根据数据处理协议，在欧盟（法兰克福）的服务器上处理。这意味着数据会被传输至马来西亚境外。网站本身由 Vercel 托管。",
		whatsappHeading: "WhatsApp 订单通知",
		whatsapp:
			"如果您在结账时勾选此选项，我们会通过 WhatsApp 向您的电话号码发送订单进度——付款、生产步骤和送货。WhatsApp 由 Meta Platforms 运营，Meta 会处理您的号码和这些信息，处理地点可能在马来西亚境外。我们不会发送其他内容，您可以屏蔽该号码以停止接收通知。",
		choiceHeading: "您的选择",
		choice:
			"若您拒绝，我们只会在不使用 Cookie 或本地存储的情况下统计访问次数，所用标识每天重置，也不会进行任何录像。您可随时在浏览器中清除本网站的数据以更改选择。",
		contactHeading: "联系我们",
		contact: "如有疑问，或要求查阅或更正您的数据，请联系：{email}",
		back: "返回主页",
	},
	whatsapp: {
		autoReply:
			"此号码仅用于发送 EzCabinet 订单通知。如需与我们的团队联系，请发送信息至 {number}",
	},
	/** The shared header's account menu and the account side nav. */
	account: {
		navHeading: "您的账户",
		myOrders: "我的订单",
		signIn: "登录",
		signOut: "退出登录",
		menuLabel: "账户菜单",
	},
	orders: {
		heading: "我的订单",
		empty: "暂无订单",
		emptyBody: "订购设计后，订单会显示在这里，并附上付款、生产和配送状态。",
		startPlanning: "开始设计",
		statusAwaiting: "待付款",
		statusPaid: "已付款",
		statusCancelled: "已取消",
		orderedOn: "下单于 {date}",
		unitsOne: "{room} · 1 件",
		unitsOther: "{room} · {count} 件",
		stageNotStarted: "尚未开始生产",
		payNow: "立即付款",
		viewOrder: "查看订单",
	},
	signIn: {
		heading: "登录",
		body: "保存您的设计并跟踪您的订单。",
		continueWithGoogle: "使用 Google 继续",
		error: "无法打开 Google 登录，请重试",
		nudge: "已保存在此设备上。登录后即可下单。",
		nudgeDismiss: "稍后再说",
		back: "返回主页",
	},
};
